# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Bascis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print Hello message
        run : echo "Hello, world from TestJob"

  test_job_2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run : echo "Hello World from TestJob2"
