# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Bascis
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Linting code
        run : |
          flake8 flaskapp.py
      - name: Success linting
        run : echo "Linting is successfull 
          
        
      - name: Print Hello message
        run : echo "Hello, world from TestJob"
     
      - name: Execute commands
        run : |
          echo "Hello message1"
          echo "Hello message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      - name: Current folder list
        run: ls -la
        
